import Link from 'next/link'

export default function Landing() {
  return (
    <div className="min-h-screen bg-gray-950 text-white">

      {/* Top nav */}
      <header className="sticky top-0 z-30 bg-gray-950/95 backdrop-blur-md border-b border-gray-800/70">
        <div className="max-w-6xl mx-auto px-6 h-14 flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="w-7 h-7 bg-gradient-to-br from-orange-500 to-orange-700 rounded-lg flex items-center justify-center text-xs font-black tracking-tight shadow-lg shadow-orange-900/40">
              SC
            </div>
            <span className="font-bold text-sm tracking-tight">Supply Chain Monitor</span>
            <span className="hidden sm:inline text-gray-600 text-xs font-medium">— APAC</span>
          </div>
          <nav className="flex items-center gap-4 text-sm">
            <a href="#routes" className="text-gray-400 hover:text-white transition-colors hidden sm:block">Routes</a>
            <a href="#how" className="text-gray-400 hover:text-white transition-colors hidden sm:block">How it works</a>
            <Link
              href="/app"
              className="bg-orange-600 hover:bg-orange-500 rounded-lg px-4 py-1.5 font-semibold text-sm shadow-lg shadow-orange-900/30 transition-colors"
            >
              Try Demo →
            </Link>
          </nav>
        </div>
      </header>

      {/* Hero */}
      <section className="px-6 pt-20 pb-24">
        <div className="max-w-4xl mx-auto text-center">
          <div className="inline-flex items-center gap-2 bg-orange-950/50 ring-1 ring-orange-800/50 rounded-full px-3 py-1 mb-7">
            <span className="relative flex h-2 w-2">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-orange-400 opacity-60" />
              <span className="relative inline-flex rounded-full h-2 w-2 bg-orange-500" />
            </span>
            <span className="text-xs text-orange-300 font-medium tracking-wide">Live · 10 APAC corridors monitored</span>
          </div>

          <h1 className="text-5xl sm:text-6xl font-bold tracking-tight mb-6 leading-[1.05]">
            Know which trade routes
            <span className="block bg-gradient-to-r from-orange-400 to-amber-300 bg-clip-text text-transparent mt-2">
              are about to cost you money
            </span>
          </h1>

          <p className="text-lg text-gray-400 max-w-2xl mx-auto mb-10 leading-relaxed">
            AI scans live news across 10 APAC trade corridors — Strait of Malacca, Red Sea, Taiwan Strait, and more — and tells you which lanes are at risk, why, and what to do about it. No login required.
          </p>

          <div className="flex flex-col sm:flex-row items-center justify-center gap-3">
            <Link
              href="/app"
              className="w-full sm:w-auto bg-orange-600 hover:bg-orange-500 active:bg-orange-700 rounded-xl px-7 py-3.5 font-semibold text-base shadow-lg shadow-orange-900/30 transition-all duration-150 inline-flex items-center justify-center gap-2"
            >
              Scan APAC Routes
              <span>→</span>
            </Link>
            <Link
              href="/app#detail"
              className="w-full sm:w-auto bg-gray-800/70 hover:bg-gray-700/70 ring-1 ring-gray-700/60 rounded-xl px-7 py-3.5 font-medium text-base text-gray-300 hover:text-white transition-all duration-150 inline-flex items-center justify-center gap-2"
            >
              Deep Dive a Single Route
            </Link>
          </div>

          <p className="text-xs text-gray-600 mt-6">
            Free demo · pulls live news at scan time · risk scores generated by AI in ~20s
          </p>
        </div>
      </section>

      {/* Routes monitored */}
      <section id="routes" className="px-6 py-16 border-t border-gray-800/60">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-10">
            <p className="text-xs font-bold text-orange-400 uppercase tracking-widest mb-2">What gets monitored</p>
            <h2 className="text-3xl font-bold tracking-tight">10 APAC corridors out of the box</h2>
            <p className="text-gray-500 mt-3 max-w-xl mx-auto">Custom routes too — Tanjung Pelepas, Banda Sea, any lane you care about. Just type it in.</p>
          </div>

          <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-2.5">
            {[
              'Strait of Malacca',
              'Port Klang',
              'South China Sea',
              'Red Sea / Suez',
              'Trans-Pacific',
              'Asia → Europe',
              'Port of Singapore',
              'Port of Shanghai',
              'Lombok Strait',
              'Taiwan Strait',
            ].map(r => (
              <div key={r} className="bg-gray-900 ring-1 ring-gray-800 rounded-xl px-3 py-3 text-center hover:ring-orange-700/40 transition-colors">
                <span className="text-sm text-gray-300 font-medium">{r}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* What you get */}
      <section className="px-6 py-16 border-t border-gray-800/60">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-12">
            <p className="text-xs font-bold text-orange-400 uppercase tracking-widest mb-2">What you get</p>
            <h2 className="text-3xl font-bold tracking-tight">Five outputs per scan</h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {[
              {
                title: 'Risk Score & Level',
                desc: 'A single 0–100 score and LOW/MEDIUM/HIGH/CRITICAL classification — calibrated for ops directors and risk committees.',
                color: 'from-red-500/20 to-red-700/10',
                ring: 'ring-red-800/40',
                emoji: '🔥',
              },
              {
                title: 'Active Disruptions',
                desc: 'Specific events affecting the route right now — strikes, weather, geopolitics, congestion, regulatory shifts.',
                color: 'from-orange-500/20 to-orange-700/10',
                ring: 'ring-orange-800/40',
                emoji: '⚠️',
              },
              {
                title: 'Affected Commodities',
                desc: 'Which goods flowing through this lane are at risk — semiconductors, palm oil, electronics, automotive.',
                color: 'from-amber-500/20 to-amber-700/10',
                ring: 'ring-amber-800/40',
                emoji: '📦',
              },
              {
                title: 'Impact Assessment',
                desc: 'Plain-language read on cost, transit-time, and inventory implications. Briefing-ready, no fluff.',
                color: 'from-yellow-500/20 to-yellow-700/10',
                ring: 'ring-yellow-800/40',
                emoji: '📊',
              },
              {
                title: 'Live News Sources',
                desc: 'The actual headlines and snippets that drove the score — auditable, dated, attributed to source.',
                color: 'from-blue-500/20 to-blue-700/10',
                ring: 'ring-blue-800/40',
                emoji: '📰',
              },
              {
                title: 'Mitigations & Outlook',
                desc: 'Numbered actions you can take — reroute, build buffer stock, hedge contracts — plus 7–14 day forward view.',
                color: 'from-emerald-500/20 to-emerald-700/10',
                ring: 'ring-emerald-800/40',
                emoji: '✅',
              },
            ].map(f => (
              <div key={f.title} className={`relative bg-gray-900 rounded-2xl p-5 ring-1 ${f.ring} hover:ring-gray-600/70 transition-all overflow-hidden`}>
                <div className={`absolute inset-0 bg-gradient-to-br ${f.color} opacity-30 pointer-events-none`} />
                <div className="relative">
                  <div className="text-2xl mb-3">{f.emoji}</div>
                  <h3 className="text-base font-bold text-white mb-1.5">{f.title}</h3>
                  <p className="text-sm text-gray-400 leading-relaxed">{f.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How it works */}
      <section id="how" className="px-6 py-16 border-t border-gray-800/60 bg-gray-950/60">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-12">
            <p className="text-xs font-bold text-orange-400 uppercase tracking-widest mb-2">How it works</p>
            <h2 className="text-3xl font-bold tracking-tight">Three modes, one engine</h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
            {[
              { n: 1, title: 'Network Snapshot', desc: 'One click scans all 10 corridors in parallel. Returns a colour-coded grid of risk levels — perfect for daily standups.' },
              { n: 2, title: 'Route Deep Dive', desc: 'Pick a single route and get the full report: live news, disruption signals, commodities at risk, mitigations.' },
              { n: 3, title: 'Custom Lane', desc: 'Type in any lane or region — Tanjung Pelepas, Banda Sea, Asia-Australia. The AI assesses it the same way.' },
            ].map(s => (
              <div key={s.n} className="bg-gray-900 ring-1 ring-gray-800 rounded-2xl p-6">
                <div className="w-10 h-10 bg-orange-600/20 ring-1 ring-orange-500/40 rounded-xl flex items-center justify-center text-orange-400 font-bold text-lg mb-4">
                  {s.n}
                </div>
                <h3 className="text-base font-bold mb-2">{s.title}</h3>
                <p className="text-sm text-gray-400 leading-relaxed">{s.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Use cases */}
      <section className="px-6 py-16 border-t border-gray-800/60">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-10">
            <p className="text-xs font-bold text-orange-400 uppercase tracking-widest mb-2">Who it&apos;s for</p>
            <h2 className="text-3xl font-bold tracking-tight">Built for the people who get the panicked email at 6pm</h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {[
              {
                title: 'Procurement & Supply Planners',
                body: 'Spot lane risk before it becomes a stockout. Brief the CFO with audit-trail-ready impact assessments instead of vibes.',
              },
              {
                title: 'Logistics Ops Managers',
                body: 'Reroute earlier, build buffers earlier, hedge contracts earlier. Stop being the last to know about a Suez incident.',
              },
              {
                title: 'Risk & Insurance Teams',
                body: 'Continuous APAC risk visibility without a Bloomberg terminal. Quantify exposure for renewals and reinsurance discussions.',
              },
              {
                title: 'C-Suite & Board Reporting',
                body: 'Generate weekly disruption snapshots in 30 seconds — risk levels, hotspots, mitigations — paste straight into the deck.',
              },
            ].map(u => (
              <div key={u.title} className="bg-gray-900 ring-1 ring-gray-800 rounded-2xl p-6">
                <h3 className="text-base font-bold mb-2 text-white">{u.title}</h3>
                <p className="text-sm text-gray-400 leading-relaxed">{u.body}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Final CTA */}
      <section className="px-6 py-20 border-t border-gray-800/60">
        <div className="max-w-3xl mx-auto text-center">
          <h2 className="text-3xl sm:text-4xl font-bold tracking-tight mb-5">
            Stop guessing about your trade lanes
          </h2>
          <p className="text-gray-400 mb-8 max-w-xl mx-auto">
            One click, ~20 seconds, full APAC network read. Free demo, no login, no credit card.
          </p>
          <Link
            href="/app"
            className="inline-flex items-center gap-2 bg-orange-600 hover:bg-orange-500 active:bg-orange-700 rounded-xl px-8 py-4 font-semibold text-base shadow-lg shadow-orange-900/30 transition-all"
          >
            Launch Demo
            <span>→</span>
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-gray-800/60">
        <div className="max-w-6xl mx-auto px-6 py-8 flex flex-col sm:flex-row items-center justify-between gap-3">
          <div className="flex items-center gap-2">
            <div className="w-5 h-5 bg-orange-600 rounded-md flex items-center justify-center text-[10px] font-black">
              SC
            </div>
            <p className="text-xs text-gray-500 font-medium">Supply Chain Disruption Monitor</p>
          </div>
          <div className="flex items-center gap-4 text-xs text-gray-600">
            <a href="https://aibizmy.com" target="_blank" rel="noopener" className="hover:text-gray-300 transition-colors">aibizmy.com</a>
            <span>·</span>
            <span>AI-powered · APAC focused</span>
          </div>
        </div>
      </footer>
    </div>
  )
}
